name: questions_aqida
description: Questions aqida
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  path_provider: ^1.6.21
  sqflite: ^1.3.1+1
  flutter_slidable: ^0.5.7
  flushbar: ^1.10.4
  flutter_html: ^1.0.2
  modal_bottom_sheet: ^0.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/databases/qst.db
  fonts:
    - family: Gilroy
      fonts:
        - asset: font/gilroy.ttf